name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dev requirements
        run: python3 -m pip install -r requirements-dev.txt

      - name: Run pytest
        run: python3 -m pytest .
